version: '3.8'
services:
  frontend:
    build:
      context: ./frontend
      target: production
    ports:
      - "80:80"
    environment:
      - NODE_ENV=production

  backend:
    build:
      context: ./backend
      target: production
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=production
