version: '3.8'
services:
  frontend:
    build: ./frontend
    ports:
      - "80:80"
    depends_on:
      - backend
  backend:
    # Backend service configuration goes here
  mongo:
    # MongoDB service configuration goes here
version: '3.8'
services:
  frontend:
    build: ./frontend
    ports:
      - "80:80"
    depends_on:
      - backend
  backend:
    # Backend service configuration goes here
  mongo:
    # MongoDB service configuration goes here
