apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.prod.yml
    kompose.version: 1.32.0 (765fde254)
  labels:
    io.kompose.service: trip-service
  name: trip-service
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: trip-service
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose.prod.yml
        kompose.version: 1.32.0 (765fde254)
      labels:
        io.kompose.network/ride-sharing-default: "true"
        io.kompose.service: trip-service
    spec:
      containers:
        - env:
            - name: DB_CONNECTION
              value: "mongodb://mongodb/tripService"
            - name: NODE_ENV
              value: "production"
            - name: JWT_SECRET
              value: "9a3f5dbdfb1855550344bb0525b7f3da6052be826bb8adf3487f592da32d2f4016cf7d14eeb0e970fae6b3a9861916ae0d60822c93d43b8d2064f2a6654c6c88"
            - name: USER_SERVICE_URL
              value: "http://user-service:3001"
          image: gcr.io/ride-sharing-app-419819/ride-sharing-trip-service:latest
          name: trip-service
          ports:
            - containerPort: 3002
              hostPort: 3002
              protocol: TCP
      restartPolicy: Always
